### ISSUE TITLE
Add "Engineering Docs" to navigation

### ISSUE THREAD

**Issue by gbraad** [crc-org/blog#20]

**Comment by gbraad** [comment]
On Hold due to issue: #21 causes by https://github.com/crc-org/blog/actions/runs/12025317350/job/33522257802 => Pinned to specific version of Hugo.

**Comment by cfergeau** [comment]
> On Hold due to issue: [#21](https://github.com/crc-org/blog/issues/21) causes by https://github.com/crc-org/blog/actions/runs/12025317350/job/33522257802 => Pinned to specific version of Hugo.

Imo this is a hint that it is time to update our hugo setup. Pinning to an older version is burying our head in the sand and is likely to byte us in the future.

**Comment by gbraad** [comment]
Already moved to a newer version. However, using `latest` is usually not a best practices as it can lead to unexpected issues, unless tests are involved to ensure no changes in rendering happened that are unwanted.
