### ISSUE TITLE
Create container for page/blog generation

### ISSUE THREAD

**Issue by gbraad** [crc-org/blog#21]
As seen in https://github.com/crc-org/blog/actions/runs/12025317350/job/33522257802, the version of Hugo may be newer and might cause issues. Let's update the blog and create a static container to prevent this kind of issues in future.

**Comment by cfergeau** [comment]
The problem is https://mitrich.me/en/posts/anubis-closed/ , not the hugo version per-se

**Comment by cfergeau** [comment]
See also https://github.com/crc-org/blog/issues/20#issuecomment-2500037055
